site_name: Impact Analysis fro Balto Customer Success Managers
site_description: Brought to you by Balto Data Science
site_author: Ryan Volkert
site_url: ""
theme: readthedocs
markdown_extensions:
    - codehilite
nav:
    - Overview: index.md
    - Data: data.md
    - FAQ: faq.md
