site_name: Impact Analysis v2.0 for Balto Customer Success Managers
site_description: Brought to you by Balto Data Science
site_author: Ryan Volkert, Jordan Navin
site_url: ""
theme: readthedocs
markdown_extensions:
    - codehilite
nav:
    - Impact Analysis v2.0: index.md
    - Other FAQ: faq.md
    - Example Report:
        ACI SharkNinja AHT Analysis: example_report.html
