site_name: Impact Analysis for Balto Customer Success Managers
site_description: Brought to you by Balto Data Science
site_author: Ryan Volkert
site_url: ""
theme: readthedocs
markdown_extensions:
    - codehilite
nav:
    - Overview: index.md
    - Data: data.md
    - FAQ: faq.md
    - Example Report:
        Shark/Ninja AHT Analysis: example_report.html
    - Playbook Report for Balto CSMs:
        - Playbook Report Overview: playbook_report.md 
        - Playbook Report FAQ: FAQ_playbook.md
        - Example Playbook Report:
               Quotewizard Outbound Report: example_pb_report.html
